# BE CAREFUL MODIFYING THIS FILE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility
spec:
  selector:
    matchLabels:
      app: eligibility
  replicas: 3
  template:
    metadata:
      labels:
        app: eligibility
    spec:
      containers:
      - name: eligibility
        image: gcr.io/gems-org/eligibility:VERSION
        command: ["./eligibility"]
        args: ["--env=production"]
        env:
        - name: ELIG_DB_HOST
          value: "cloudsql-proxy"
        - name: ELIG_DB_PORT
          value: "3306"
        - name: ELIG_DB_NAME
          value: "eligibility"
        - name: ELIG_DB_USER
          valueFrom:
            configMapKeyRef:
              name: eligibility-data
              key: ELIG_DB_USER
        - name: ELIG_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eligibility-data
              key: ELIG_DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: eligibility-data
              key: JWT_SECRET
        resources: {}
      
---
apiVersion: batch/v1
kind: Job
metadata:
  name: eligibility-migration
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: eligibility-migration
    spec:
      containers:
      - name: eligibility-migration
        image: gcr.io/gems-org/eligibility-migration:VERSION
        args: ["composeup"]
        env:
        - name: ELIG_DB_HOST
          value: "cloudsql-proxy"
        - name: ELIG_DB_PORT
          value: "3306"
        - name: ELIG_DB_NAME
          value: "eligibility"
        - name: ELIG_DB_USER
          valueFrom:
            configMapKeyRef:
              name: eligibility-data
              key: ELIG_DB_USER
        - name: ELIG_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eligibility-data
              key: ELIG_DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
---

apiVersion: v1
kind: Service
metadata:
  name: eligibility
spec:
  selector:
    app: eligibility
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

